### ISSUE TITLE
[Proposal] Kubecon Demo that shows infrastructure flagging with CUE/Signed images

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/ofep#14]
I believe we need to have some really good examples of feature-flagging on both the client/developer side and also used in infrastructure scenarios.

 I propose that we combine several key technologies to build a very compelling demo.
- Open feature operator + flagD
- Sigstore/cosign 
- CUE

The following proposal is to build a demo image admission application that could potentially be spun out into a real project eventually. The tie into OpenFeature is that it would read its flag configuration to decide whether the image signing validator is turned on or off.

Comments welcome. 

![image](https://user-images.githubusercontent.com/1235925/176728161-d6aa51a8-304a-4936-b7de-5752e44bb3e2.png)

Work involved:
- Write a CUE based `ievaluator`
- Extend Openfeature operator to read `CUE` based configuration
- Write the demo image admission controller

End-user takeaways:

- Featureflags can be used at the infrastructure level
- OpenFeature operator and FlagD allow you to build against them with no real work required to integrate ( evaluator included ).

**Comment by beeme1mr** [comment]
Hey Alex, thanks for putting together the proposal! I think CUE would be a perfect fit for simplifying flag creation and validation but I'm not sure how it would be used in the `ievaluator`. Could you elaborate on that part of the proposal?

**Comment by toddbaert** [comment]
I think this is a cool idea, and I like the idea of the CUE flag definition.

Will you use json-logic for targeting/rules? Or not implement targeting/rules? You could try CEL if it's of interested to you... I'm not sure if you can do decisions or general rule engines in CUE.

**Comment by toddbaert** [comment]
> Hey Alex, thanks for putting together the proposal! I think CUE would be a perfect fit for simplifying flag creation and validation but I'm not sure how it would be used in the ievaluator. Could you elaborate on that part of the proposal?

the ievaluator doesn't just evaluate rules, but also flags. It understands the flag strcuture.

**Comment by beeme1mr** [comment]
> The ievaluator doesn't just evaluate rules, but also flags. It understands the flag structure. It's the "brain" that understands the flag definition. All the other interfaces are completely unaware of that.

Got it, that makes sense. Validation using CUE is extremely powerful and easier to write than JSON schema (in my opinion).



> Will you use json-logic for targeting/rules? Or not implement targeting/rules? You could try [CEL](https://github.com/google/cel-spec) if it's of interest to you... I'm not sure if you can do decisions or general rule engines in CUE.

I would prefer to not introduce another rules engine.

**Comment by toddbaert** [comment]
> I would prefer to not introduce another rules engine.

I don't mind so much, but I guess we could keep the rules in json-logic in that case, or not support them.

**Comment by AlexsJones** [comment]
I was thinking of using CUE as a superset for the user to express themselves and when it's brought into flagd it gets interpreted down into pure json and plays ball with the existing engine.

**Comment by dlorenc** [comment]
Just stumbled on this and wanted to point out the sigstore policy-controller, which uses Cue to define policy for which images to admit. I'd love to collaborate and see if we can combine these demos :)

https://github.com/sigstore/policy-controller

**Comment by AlexsJones** [comment]
I had the chance to take a look at the controller and it looks like for us to integrate with Open Feature. 
The easiest way seems to be for us to create a service that either creates or deletes Policy resources

https://github.com/sigstore/policy-controller/blob/main/pkg/webhook/validator.go#L178

**Comment by AlexsJones** [comment]
https://github.com/open-feature/research/blob/main/002-OFEP-kubecon-demo.md

Keeping this open a little as we have some folks in this thread who are not familiar that we have moved to a pull-request based review process for research
