### ISSUE TITLE
[Proposal] [flagD] Flag update subscribers via gRPC streams

### ISSUE THREAD

**Issue by james-milligan** [open-feature/ofep#18]
Using gRPC streams we can create subscribers to allow for client side updates to be driven from flag value changes in situations where a flag will not be re-evaluated, such as those involved in startup. 

Next steps:
1. What is the process that will be used to subscribe to changes on a flag - will multiple client connections be spun up or will one connection handle all updates?
2. What will the schema look like for the subscription requests and updates - will these changes be incorporated into the existing interface or will they sit on a separate one?
3. If we choose to implement this in the rest interface of flagd, how will this be done? (websockets, server push or not at all?)

**Comment by beeme1mr** [comment]
@james-milligan, is this issue still relevant?

**Comment by james-milligan** [comment]
> @james-milligan, is this issue still relevant?

no, will close
