### ISSUE TITLE
[GSoC] Streamlined OFEP Processes

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/ofep#48]
This ticket is a part of CNCF Google Summer of Code (GSoC) program: https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md#streamlined-openfeature-enhancement-proposal-process

## Overview

It’s important that non-trivial changes in OpenFeature are agreed upon and documented. The OpenFeature Enhancement Proposal process should be used to gather community feedback and ensure overall alignment with the project. This process should be as streamlined as possible to encourage community participation.

## Requirements

- [x] #63
- [x] #72
- [x] Send reminders when an OFEP PR becomes stale
- [x] #73
- [x] #75
- [x] #74
- [x] #76

## Resources

- [OpenFeature OFEP Repo](https://github.com/open-feature/ofep)
- [OpenTelemetry OTEP Repo](https://github.com/open-telemetry/oteps)
- [Python Enhancement Proposals](https://peps.python.org/pep-0001/)
- [Tool for Architecture Decision Records](https://github.com/butonic/adr-tools)

**Comment by YunDudali** [comment]
I am interested in this project, how can I contact you

**Comment by beeme1mr** [comment]
Hey @YunDudali, thanks for your interest. This issue is for the [Google Summer of Code (GSoC)](https://summerofcode.withgoogle.com/). If you're interested, I would encourage you to get involved with GSoC when it opens on [March 20th](https://developers.google.com/open-source/gsoc/timeline#march_20_-_1800_utc).

**Comment by octonawish-akcodes** [comment]
I am interested in this project, Is there any slack link

**Comment by beeme1mr** [comment]
Hi @octonawish-akcodes, yep! we're on the [CNCF Slack Workspace](https://slack.cncf.io) under the `#openfeature` channel.

**Comment by beeme1mr** [comment]
🥳 The CNCF has officially been accepted as a mentoring organization for Google Summer of Code (GSoC). If you're interested in participating as a GSoC contributors, please review [this discussion](https://github.com/cncf/mentoring/discussions/848). It contains timelines and requirements.

**Comment by octonawish-akcodes** [comment]
thank you

**Comment by MatrixX-X** [comment]
Hi, I am new to open source.
I am interested in this project, is there anything that i can do to increase my chance of getting selected for this project

**Comment by beeme1mr** [comment]
Hey @MatrixX-X, I updated the issue to include a bit more information. Please let me know if anything is unclear.

**Comment by Lan-ce-lot** [comment]
Hey @beeme1mr, I am a master from SEL laboratory of Zhejiang University, familiar with cloud native, python and github action. Now I am very interested in the OpenFeature community and hope to participate in the community through this issue.

**Comment by beeme1mr** [comment]
Hi @Lan-ce-lot, welcome and thanks for reaching out! There's been a lot of interest in working on this issue for GSoC. Please refer to this [GitHub discussion](https://github.com/cncf/mentoring/discussions/848) for more information on how you can get involved in GSoC in order to increase your chances of getting selected.

**Comment by satyampsoni** [comment]
Is there any format for the GSOC Proposal?

**Comment by beeme1mr** [comment]
Hey @satyampsoni, please make sure you follow the GSoC proposal requirements listed [here](https://google.github.io/gsocguides/student/writing-a-proposal). It's also [recommended](https://github.com/cncf/mentoring/discussions/892#discussioncomment-5397864) to create your proposal using a tool that allows us to provide feedback (e.g. Google docs, hackmd.io). Please note that you would still be required to have the proposal submitted to GSoC system!

**Comment by LetsGetStartedWithBub** [comment]
Hi @beeme1mr, I submitted my proposal can you please check it once and let me know if something needs to be modified.

**Comment by beeme1mr** [comment]
Hey @LetsGetStartedWithBub, the proposal looks good. Thanks for your interest in the project 👍

**Comment by LetsGetStartedWithBub** [comment]
Hey @beeme1mr , I just updated my proposal with few more details. Please go through to it once. 
Thank you.
