### ISSUE TITLE
Document the OFEP lifecycle

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/ofep#63]
Stages:

1. Clear main readme and contribution guide
2. Issue template
3. PR based on a template
4. Set reviewers automatically based on OFEP settings
5. Once the appropriate number of approvals have been reached, post a message that the OFEP will be merged after X number of days unless someone objects
6. Automerge after the defined timeframe
7. Publish to the openfeature.dev website

**Comment by mihirm21** [comment]
@beeme1mr Could you elaborate on the first section, i.e., clear main readme and contribution guide
